<a href="https://colab.research.google.com/github/suganthan0001/Machine-Learning/blob/main/usingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ls = [14,34,56,78]

In [3]:
arr = np.array(ls)

In [4]:
arr

array([14, 34, 56, 78])

In [5]:
arr[0]

14

In [6]:
arr[2:5]

array([56, 78])

In [7]:
arr[len(ls)-1]

78

In [8]:
arr.shape

(4,)

In [9]:
arr[1:3] = 44

In [10]:
arr

array([14, 44, 44, 78])